version: '3'

services:
  frontend:
    image: sample-image
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: npm install
    #working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=5173
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./svelte.config.js:/app/svelte.config.js
